name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish ./PortfolioSiteNEW/PortfolioSiteNEW/PortfolioSiteNEW.csproj -c Release -o ./published
      
      - name: Set GitHub Pages base path
        run: sed -i 's|<base href="/" />|<base href="/PortfolioSiteNEW/" />|' ./published/wwwroot/index.html
      
      - name: Add .nojekyll
        run: touch ./published/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./published/wwwroot
          publish_branch: gh-pages
